<?xml version="1.0" encoding="utf-8"?><Database Name="market" Class="marketDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\market.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="WpfApp1.Properties.Settings" SettingsPropertyName="marketConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BillTbl" Member="BillTbls">
    <Type Name="BillTbl">
      <Column Name="BillId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SellerName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BillDate" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TotAmt" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.CatTbl" Member="CatTbls">
    <Type Name="CatTbl">
      <Column Name="CatId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CatName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CatDesc" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ProdTbl" Member="ProdTbls">
    <Type Name="ProdTbl">
      <Column Name="ProdId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProdName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProdQty" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProdPrice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProdCat" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SellerTbl" Member="SellerTbls">
    <Type Name="SellerTbl">
      <Column Name="SellerId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SellerName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SellerAge" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SellerPhone" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SellerPassword" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>